core:
  allowedOrigins:
    - https://auth.vibelify.com
domain: https://auth.vibelify.com
googleAuth:
  key: a
  secret: b
facebookAuth:
  key: a
  secret: b
domainAuth: https://auth.vibelify.com
spaceapiAuth: zo1CoYTlKQnsSkAIHJTU5BGN3C2Acv0KJFeV8DqqmWx1TnV6Abb7DydBuRJSQDgJ