core:
  allowedOrigins:
    - https://auth.vibeit.co
domain: https://auth.vibeit.co
googleAuth:
  key: a
  secret: b
facebookAuth:
  key: a
  secret: b
domainAuth: https://auth.vibeit.co
spaceapiAuth: zo1CoYTlKQnsSkAIHJTU5BGN3C2Acv0KJFeV8DqqmWx1TnV6Abb7DydBuRJSQDgJ